### ISSUE TITLE
i3lock not recognising i3lcc

### ISSUE THREAD

**Issue by Thanatos0173** [mgord9518/i3lcc#2]
So i3lcc is working fine, however, when I type the command `i3lock`, the old (boring) i3lock screen is showing, and not the one configured with i3lcc.

**Comment by Thanatos0173** [comment]
Ok, so I have figured the issue (and my problem was mostly because I was dumb). Hence, I have modified your source code to add a button that allow me to copy the i3lock command that I need to type. I tried to make a pull request but you have blocked it :/. Let me know if you want my code.

**Comment by mgord9518** [comment]
I'd love a PR! It's strange that it was blocked, maybe my repository is incorrectly configured. Did you use the Git command or the "modify file" feature in GitHub?

**Comment by Thanatos0173** [comment]
Hey, sorry for being so long to answer.
I don't really remember how I tried to do a pull request to be honest. I think it was through git command, because I mainly use that over github. I can try again if you want.

**Comment by mgord9518** [comment]
If it's just modifying a single file it might be easiest to just edit the code in GH, paste in the changes and PR from there

I'm not really sure how the GH permissions work with the git command, I've never used it to commit to a repo I don't have write access to
